//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopShippersInfo:BaseModel
    {
        long _id;
        public long Id { get{ return _id; } set{ _id=value;} }
        public long ShopId { get; set; }
        public bool IsDefaultSendGoods { get; set; }
        public bool IsDefaultGetGoods { get; set; }
        public string ShipperTag { get; set; }
        public string ShipperName { get; set; }
        public int RegionId { get; set; }
        public string Address { get; set; }
        public string TelPhone { get; set; }
        public string Zipcode { get; set; }
        public string WxOpenId { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<float> Latitude { get; set; }
    }
}
